# Generated by Django 5.1 on 2024-08-28 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_codigo', models.CharField(max_length=20)),
                ('_nombre_materia', models.CharField(max_length=50)),
                ('_creditos', models.CharField(max_length=10)),
                ('_horario', models.TextField(max_length=100)),
            ],
        ),
    ]
